import bcrypt from 'bcryptjs';

const data = {

  admins: [
    {
      name: 'admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
    {
      name: 'Johnadmin',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
  ],
  users: [
    {
      name: 'jayesh',
      email: 'jayesh@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p7.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'boAt Rockerz 560 Bluetooth',
      category: 'Headphones',
      image: '/images/p8.jpeg',
      price: 120,
      countInStock: 200,
      brand: 'Boat',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'acer Aspire 7 Core i5',
      category: 'Laptops',
      image: '/images/p9.jpeg',
      price: 920,
      countInStock: 40,
      brand: 'Acer',
      rating: 4.5,
      numReviews: 12345,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
     {
      name: 'AMERICAN TOURISTER Bag',
      category: 'Backpacks',
      image: '/images/p11.jpeg',
      price: 20,
      countInStock: 150,
      brand: 'American Tourister',
      rating: 4.5,
      numReviews: 26787,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
     {
      name: 'Fastrack Watch',
      category: 'Watches',
      image: '/images/p10.jpeg',
      price: 30,
      countInStock: 220,
      brand: 'Fastrack',
      rating: 4.5,
      numReviews: 1777,
      description: 'high quality product',
    }
  ],
};
export default data;